wifi: Fix StringIndexOutOfBoundsException due to insufficient checks
Fix an error where a user can get stuck at the bootscreen.
Error seen on affected devices:

*** FATAL EXCEPTION IN SYSTEM PROCESS: WifiStateMachine
java.lang.StringIndexOutOfBoundsException: length=0; index=0

Change-Id: Ib6626ec88a2329358f9b5c85fa4d4fb34509f609